export const MAP_REASONS_TO_LOCATION = 'MAP_REASONS_TO_LOCATION'

// Failed Applicants Actions

export const FETCH_ALL_DATA = 'FETCH_ALL_DATA'

export const FETCH_SALES_DATA = 'FETCH_SALES_DATA'
export const FETCH_SALES_DATA_SUCCESS = 'FETCH_SALES_DATA_SUCCESS'
export const FETCH_SALES_DATA_FAILED = 'FETCH_SALES_DATA_FAILED'

export const POST_SALES_DATA = 'POST_SALES_DATA'
export const POST_SALES_DATA_SUCCESS = 'POST_SALES_DATA_SUCCESS'
export const POST_SALES_DATA_FAILED = 'POST_SALES_DATA_FAILED'

export const DELETE_SALES_DATA_ENTRIES = 'DELETE_SALES_DATA_ENTRIES'
export const DELETE_SALES_DATA_ENTRIES_SUCCESS =
  'DELETE_SALES_DATA_ENTRIES_SUCCESS'
export const DELETE_SALES_DATA_ENTRIES_FAILED =
  'DELETE_SALES_DATA_ENTRIES_FAILED'

export const FETCH_SALES_TALLY_DATA = 'FETCH_SALES_TALLY_DATA'
export const FETCH_SALES_TALLY_DATA_SUCCESS = 'FETCH_SALES_TALLY_DATA_SUCCESS'
export const FETCH_SALES_TALLY_DATA_FAILED = 'FETCH_SALES_TALLY_DATA_FAILED'

export const PUT_SALES_TALLY_DATA = 'PUT_SALES_TALLY_DATA'
export const PUT_SALES_TALLY_DATA_SUCCESS = 'PUT_SALES_TALLY_DATA_SUCCESS'
export const PUT_SALES_TALLY_DATA_FAILED = 'PUT_SALES_TALLY_DATA_FAILED'
