export const FETCH_FEEDBACK_DATA = 'FETCH_FEEDBACK_DATA'
export const FETCH_FEEDBACK_DATA_SUCCESS = 'FETCH_FEEDBACK_DATA_SUCCESS'
export const FETCH_FEEDBACK_DATA_FAILED = 'FETCH_FEEDBACK_DATA_FAILED'

export const POST_FEEDBACK_DATA = 'POST_FEEBACK_DATA'
export const POST_FEEDBACK_DATA_SUCCESS = 'POST_FEEDBACK_DATA_SUCCESS'
export const POST_FEEDBACK_DATA_FAILED = 'POST_FEEDBACK_DATA_FAILED'

export const DELETE_FEEDBACK_DATA_ENTRIES = 'DELETE_FEEDBACK_DATA_ENTRIES'
export const DELETE_FEEDBACK_DATA_ENTRIES_SUCCESS =
  'DELETE_FEEDBACK_DATA_ENTRIES_SUCCESS'
export const DELETE_FEEDBACK_DATA_ENTRIES_FAILED =
  'DELETE_FEEDBACK_DATA_ENTRIES_FAILED'

export const FETCH_TALLY_DATA = 'FETCH_TALLY_DATA'
export const FETCH_TALLY_DATA_SUCCESS = 'FETCH_TALLY_DATA_SUCCESS'
export const FETCH_TALLY_DATA_FAILED = 'FETCH_TALLY_DATA_FAILED'

export const POST_TALLY_DATA = 'POST_TALLY_DATA'
export const POST_TALLY_DATA_SUCCESS = 'POST_TALLY_DATA_SUCCESS'
export const POST_TALLY_DATA_FAILED = 'POST_TALLY_DATA_FAILED'
